# Generated by Django 2.1.2 on 2018-11-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbyName', models.CharField(max_length=250)),
                ('hobbyDesc', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('profileImage', models.ImageField(upload_to='profile_images')),
                ('email', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=1)),
                ('dateOfBirth', models.DateField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='hobby',
            name='users',
            field=models.ManyToManyField(to='matchingsite.User'),
        ),
    ]
