# Generated by Django 2.1.2 on 2018-12-07 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchingsite', '0004_auto_20181129_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AlterField(
            model_name='hobby',
            name='users',
            field=models.ManyToManyField(to='matchingsite.Profile'),
        ),
    ]
