# Generated by Django 2.1.2 on 2018-12-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchingsite', '0005_auto_20181207_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='users',
        ),
        migrations.AddField(
            model_name='profile',
            name='hobbies',
            field=models.ManyToManyField(to='matchingsite.Hobby'),
        ),
    ]
